import NavBar from '../components/navbar'
import Head from 'next/head'
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
  return (
    <div className='min-w-min'>
      <Head>
        <title>Marvel (next.js)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className=''>
        <Component {...pageProps} />
      </main> 
    </div>
  )
}

export default MyApp
